return {
	require("plugins.bufferline"),
	require("plugins.cmp"),
	require("plugins.colorscheme"),
	require("plugins.comment"),
	require("plugins.copilot"),
	require("plugins.fugitive"),
	require("plugins.lualine"),
	require("plugins.mason"),
	require("plugins.neotree"),
	require("plugins.project"),
	require("plugins.telescope"),
	require("plugins.treesitter"),
	require("plugins.undotree"),
	require("plugins.venvselect"),
}
